env:
 - CABALVER=1.20 GHCVER=7.0.4
 - CABALVER=1.20 GHCVER=7.2.2
 - CABALVER=1.20 GHCVER=7.4.2
 - CABALVER=1.20 GHCVER=7.6.3
 - CABALVER=1.20 GHCVER=7.8.3
 - CABALVER=head GHCVER=7.8.3
 - CABALVER=head GHCVER=head

matrix:
 allow_failures:
  - env: CABALVER=head GHCVER=head

before_install:
 - sudo add-apt-repository -y ppa:hvr/ghc
 - sudo apt-get update -qq

install:
 - sudo apt-get install -qq cabal-install-$CABALVER ghc-$GHCVER libopenal-dev libalut-dev
 - export PATH="/opt/cabal/$CABALVER/bin:/opt/ghc/$GHCVER/bin:$PATH"

before_script:
 - cabal --version
 - cabal update
 - ghc --version
 - ghc-pkg list
 - pushd ..
 - git clone --depth=100 --quiet https://github.com/haskell-opengl/OpenGLRaw.git
 - cd OpenGLRaw
 - cabal install --enable-documentation
 - popd
 - ghc-pkg list
 - pushd ..
 - git clone --depth=100 --quiet https://github.com/haskell-opengl/GLURaw.git
 - cd GLURaw
 - cabal install --enable-documentation
 - popd
 - ghc-pkg list
 - pushd ..
 - git clone --depth=100 --quiet https://github.com/haskell-opengl/OpenGL.git
 - cd OpenGL
 - cabal install --enable-documentation
 - popd
 - ghc-pkg list
 - pushd ..
 - git clone --depth=100 --quiet https://github.com/haskell-openal/OpenAL.git
 - cd OpenAL
 - cabal install --enable-documentation
 - popd
 - ghc-pkg list

script:
 - cabal install --enable-documentation
 - cabal sdist
 - pushd examples/Basic
 - ghc --make -Wall -O2 HelloWorld.hs
 - ghc --make -Wall -O2 OpenALInfo.hs
 - ghc --make -Wall -O2 PlayFile.hs
 - popd
 - pushd examples/TestSuite
 - ghc --make -Wall -O2 TestErrorStuff.hs
 - ghc --make -Wall -O2 TestFileLoader.hs
 - ghc --make -Wall -O2 TestMemoryLoader.hs
 - ghc --make -Wall -O2 TestVersion.hs
 - ghc --make -Wall -O2 TestWaveforms.hs
 - popd

after_script:
 - ghc-pkg list
